language: go
sudo: required
services: docker
go:
  - "1.11"
install:
  - go get github.com/bradfitz/goimports
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only
script:
  - tests
  - build-binary
  - build-docker-image
jobs:
  include:
    - stage: tests
      if: repo = camptocamp/prometheus-puppetdb
      script:
        - make test
        - "$HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage"
    - stage: build-binary
      script: make
    - stage: build-docker-image
      script: docker build .
